#!/bin/bash

if [ -d "/tmp/jekyll" ]; then
    echo 'DELETING TEMP DIRECTORY'
    rm -rf "/tmp/jekyll"
    echo 'CREATING TEMP DIRECTORY'
    mkdir "/tmp/jekyll"
    mkdir "/tmp/jekyll/build"
else
    echo 'CREATING TEMP DIRECTORY'
    mkdir "/tmp/jekyll"
    mkdir "/tmp/jekyll/build"
fi

cd "/Volumes/Storage/Dropbox/Projects/jcrawford.github.com/"
git checkout dev > /dev/null 2>&1
rm -rf _site/ > /dev/null 2>&1
echo 'PROCESSING BUILD'
jekyll > /dev/null 2>&1
if [ -d "_site" ]; then
    if [ -d "/tmp/jekyll/build/" ]; then
        echo "Copying Build"
        cp -rf "_site/" "/tmp/jekyll/build/" > /dev/null 2>&1
        echo "Checking out the MASTER branch"
        git checkout master > /dev/null 2>&1
        echo "Deleting all old files"
        rm -rf *
        if [ -d "/tmp/jekyll/build/" ]; then
            echo "Copying build into MASTER branch"
            cp -rf /tmp/jekyll/build/* . > /dev/null 2>&1
            git add . > /dev/null 2>&1
            git commit -am "running site build process"
            echo "Pushing site build to Github"
            git push origin master > /dev/null 2>&1
            echo "Checking out the development branch"
            git checkout dev > /dev/null 2>&1
        else
            echo 'BUILD FAILED!!'
        fi
    else
        echo 'UNABLE TO CREATE TEMP DIRECTORY'
    fi
fi