#!/bin/bash

if [ -d "/tmp/jekyll" ]; then
    rm -rf "/tmp/jekyll"
    mkdir "/tmp/jekyll"
    mkdir "/tmp/jekyll/build"
else
    mkdir "/tmp/jekyll"
    mkdir "/tmp/jekyll/build"
fi

cd "/Volumes/Storage/Dropbox/Projects/jcrawford.github.com/"
git checkout dev > /dev/null 2>&1
rm -rf _site/ > /dev/null 2>&1
echo 'PROCESSING BUILD'
jekyll > /dev/null 2>&1
if [ -d "_site" ]; then
    if [ -d "/tmp/jekyll/build/" ]; then
        echo "COPYING BUILD"
        cp -rf "_site/" "/tmp/jekyll/build/" > /dev/null 2>&1
        echo "GOING TO MASTER"
        git checkout master > /dev/null 2>&1
        echo "DELETING OLD FILES"
        rm -rf *
        if [ -d "/tmp/jekyll/build/" ]; then
            echo "COPYING BUILD FILES"
            cp -rf /tmp/jekyll/build/* . > /dev/null 2>&1
            git add . > /dev/null 2>&1
            git commit -am "running site build process" > /dev/null 2>&1
            echo "PUSHING NEW BUILD TO GITHUB"
            git push origin master > /dev/null 2>&1
            echo "GOING TO DEV"
            git checkout dev > /dev/null 2>&1
        else
            echo 'BUILD FAILED!!'
        fi
    else
        echo 'UNABLE TO CREATE TEMP DIRECTORY'
    fi
fi